[metadata]
name = snowflake_sp_server
version = 0.1.0
description = Snowflake Stored Procedure Integration with MCP Server
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Cjaimesg/snowflake-mcp-sp-integration
author = Cjaimesg
author_email = 
license = MIT
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12

[options]
packages = find:
python_requires = >=3.12
install_requires =
    mcp[cli]>=1.9.2
    pandas>=2.2.3
    pyarrow>=20.0.0
    snowflake-connector-python>=3.15.0
    snowflake-snowpark-python>=1.32.0
    tabulate>=0.9.0
    python-dotenv>=1.0.0

[options.packages.find]
where = .

[flake8]
max-line-length = 88
extend-ignore = E203, W503
per-file-ignores = 
    __init__.py:F401